Repository FC-MINI-4/attendance-front, pull requests merged in 2023-07, with the labels that each got.

#3 settings: dev 브랜치 세팅
  .prettierrc
  src/components/common/Button.tsx
  src/components/common/Layout.tsx
  src/pages/_app.tsx
  src/pages/_document.tsx
  src/pages/index.css
  src/pages/index.tsx
  src/styles/globals.css
  src/types/ICommon.ts
  tailwind.config.js
Labels: 긴급 🚨

#5 [feat] 관리자 UI 작업
  .github/ISSUE_TEMPLATE/issue-template.md
  .github/pull_request_template.md
  .vscode/settings.json
  src/components/admin/AdminHeader.tsx
  src/components/admin/AdminMain.tsx
  src/pages/admin-duty.tsx
  src/pages/admin-leave.tsx
  src/pages/admin-manage.tsx
  src/types/IAdmin.ts
  tailwind.config.js
Labels: 진행중 💻

#11 FEAT: 관리자페이지UI수정
  src/components/admin/AdminHeader.tsx
  src/components/admin/AdminMain.tsx
  src/components/admin/DropDownFilter.tsx
  src/components/admin/EmployeeList.tsx
  src/components/admin/RequestList.tsx
  src/pages/admin-duty.tsx
  src/pages/admin-leave.tsx
  src/pages/admin-manage.tsx
  src/types/IAdmin.ts
Labels: 진행중 💻

#12 feat:달력기본기능구현
  package-lock.json
  package.json
  src/components/main/MainCalendar.tsx
  src/pages/index.tsx
  src/pages/main.tsx
  tailwind.config.js
Labels: 완료 👍

#24 FEAT: 로그인 페이지 UI 임시 구현
  src/components/auth/auth.tsx
  src/components/auth/sign-in/AuthSignInBox.tsx
  src/components/auth/sign-in/AuthSignInInput.tsx
  src/components/auth/sign-up/AuthSignUpInput.tsx
  src/components/auth/sign-up/AuthSignUpTitle.tsx
  src/pages/sign-in.tsx
  src/pages/sign-up.tsx
  src/pages/signin.tsx
Labels: 완료 👍

#25 Feat/main/header
  src/components/main/MainCalendar.tsx
  src/components/main/MainHeader.tsx
  src/pages/main.tsx
Labels: 완료 👍

#27 FEAT:임시시api작성
  package-lock.json
  package.json
  src/components/admin/AdminDropDownFilter.tsx
  src/components/admin/AdminEmployeeList.tsx
  src/components/admin/AdminMain.tsx
  src/components/admin/AdminRequestList.tsx
  src/constants/Option.tsx
  src/pages/api/AdminRequest.ts
  src/types/IAdmin.ts
Labels: 완료 👍

#28 FEAT:modify UI create
  package-lock.json
  src/components/admin/AdminEmployeeList.tsx
  src/components/admin/AdminMain.tsx
  src/components/admin/AdminMainHeader.tsx
  src/components/admin/AdminSideBar.tsx
  src/constants/Option.tsx
  src/pages/_app.tsx
  src/pages/admin-modify.tsx
Labels: 완료 👍
